export const allRoutes = {
  home: "/",
  error: "*",
  login: "/login",
  profile: "/profile",
  setting: "/setting",
  advanced: "/advanced",
  reporting: "/reporting",
  addProfile: "/add-profile",
  notification: "/notification",
  profileDetails: "/profile-details",
  requirementsDetail: "/requirement-details",
  addRequirements: "/add-requirements",
  newRequirements: "/new-requirements",
  saveRequirements: "/save-requirements",
  advancedSetting: "/advanced-setting",
  uploadBulkProfile: "/upload-bulk-profile",
  myProfile: "/my-profile",
  addProfilePopup: "/add-profile-popup",
  updateRequirements: "/update-requirements",
};
